### ISSUE TITLE
Leap Motion Core Assets not up-to-date according to docs

### ISSUE THREAD

**Issue by raffomania** [leapmotion/LeapMotionCoreAssets#163]
I'm not sure if this is the right place to report this, but I didn't find a better one.

The leap motion orion docs mention a [HandList](https://developer.leapmotion.com/documentation/orion/unity/api/Leap.HandList.html) class. This class is nowhere to be found in the core assets I found [on the official download page](https://developer.leapmotion.com/unity?id=unity5-core-assets&platform=windows&version=4.0.1).

**Comment by jo3w4rd** [comment]
Fixed (references to HandList removed). Note that the Orion assets are now in a different repository: https://github.com/leapmotion/UnityModules
