### ISSUE TITLE
Test and tune temporal warping for Daydream

### ISSUE THREAD

**Issue by jdonald** [leapmotion/LeapMotionCoreAssets#164]
@jselstad wrote:

> Temporal warping should just work in the 5.5 beta with native integration; its grabbing native hmd tracking data to work...
> 
> But we don't know what the manual warping offset should be because we haven't tested the latency of daydream's native integration
> 
> it shouldn't be an issue to add a special case for cardboard/daydream if all instances of VR.InputTracking ( https://docs.unity3d.com/ScriptReference/VR.InputTracking.html ) are replaced with the equivalent cardboard/daydream transforms inside of the Temporal Tracking .cs script

We can't do much until Unity 5.5 beta comes out, or if we work on this with Unity 5.4 + Daydream assets it might be throwaway work. Once the beta with native Daydream support is available, hopefully this is a small task.

**Comment by jo3w4rd** [comment]
Wrong repo.
